--- #YAML:1.0
name:                Sub-Pipeline
version:             0.010
abstract:            subs composed of sequential pieces
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Exception::Class:              1.22
    Sub::Exporter:                 0.95
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo Signes <rjbs@cpan.org>
